name: Hello workflow

on:
  workflow_dispatch: 
    inputs:
      environment:
        description: This is the env value where pipeline will run
        default: dev
        required: true
        type: choice
        options:
          - dev
          - test
          - prod
    
jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        run: echo "Code clone on github"
        
  build:
    needs: [code]
    runs-on: ubuntu-latest
    steps:
      - name: build cdocker container
        run: echo "Docker container build"
    
  test:
      needs: [build]
      runs-on: ubuntu-latest
      steps:
       - name: test code
         run: echo "Testing in container."
         
  deploy:
    needs: [test,build]
    runs-on: ubuntu-latest
    steps:
      - name: deploy code
        run: echo "Code Deployed"
        
