#API keys, Sensitive data, credentials, tokens, secrets, etc. should not be committed to the repository. This workflow will scan the repository for any secrets and alert the user if any are found.
name: Secrets Scan

on:
    workflow_call:
       
jobs:
    secrets-scan:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4
              with:
                fetch-depth: 0 # Fetch all history for all branches and tags
            
            - name: Run Gitleaks Scanner
              uses: gitleaks/gitleaks-action@v2
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

